# Generated by Django 5.2.4 on 2025-07-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="bangloreJobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("companyName", models.CharField(max_length=100)),
                ("jobTitle", models.CharField()),
                ("salary", models.CharField()),
                ("qualification", models.CharField()),
                ("location", models.CharField()),
                ("joiningDate", models.DateField()),
                ("address", models.CharField()),
                ("contactNumber", models.CharField()),
                ("email", models.CharField()),
                ("applyNow", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="delhiJobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("companyName", models.CharField(max_length=100)),
                ("jobTitle", models.CharField()),
                ("salary", models.CharField()),
                ("qualification", models.CharField()),
                ("location", models.CharField()),
                ("joiningDate", models.DateField()),
                ("address", models.CharField()),
                ("contactNumber", models.CharField()),
                ("email", models.CharField()),
                ("applyNow", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="puneJobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("companyName", models.CharField(max_length=100)),
                ("jobTitle", models.CharField()),
                ("salary", models.CharField()),
                ("qualification", models.CharField()),
                ("location", models.CharField()),
                ("joiningDate", models.DateField()),
                ("address", models.CharField()),
                ("contactNumber", models.CharField()),
                ("email", models.CharField()),
                ("applyNow", models.CharField()),
            ],
        ),
    ]
